# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

#page setting - disquz comment
enabled_disqus : true
#disqus_url : 'https://morgan-hexo-theme.disqus.com/embed.js'


#page setting - index excerpt (per article display length)
excerpt_length : 400

#page setting - slogan
slogan : [ "Hallo, dit is mijn blog", "嗨，這是我的博客!","안녕하세요, 제 블로그입니다.", "Hi, This is my blog!", "こんにちは、私のブログへようこそ!", "مرحبا، مرحبا بك في مدونتي" ]
slogan_random_display : false
slogan_color: "#404040"

#page setting - blog title color
title_color : "#404040"
title_background_color :  "#00C5CD"

#page setting - menu color
menu_text_color : "#5a5a5a"
menu_background_color : "#F7F7F7"

#page setting - article color
article_color : "#3498db" 
article_color_hover : "#34b2db" 
article_color_active : "#2075c1" #rgb(0, 188, 255)"

#page feature - about me
enabled_about_me : true
about_me : "About Me"
about_me_content : "虽然还没有想好怎么夸自己，单空着感觉怪怪的。"

#footer content
footer_big_content : ""
footer_small_content : ""

#github setting
theme: jekyll-theme-cayman
